Add link to ABI in README
bloxapp/ssv-network pull request #115
Opened 2022-11-14 13:44 UTC by andrew-blox

2022-11-14 15:21 UTC, lior-blox commented
@andrew-blox lets add it as a template for abi based on tags - please include an example
In addition lets open an issue to auto-generate a link in readme for

2022-11-14 15:22 UTC, lior-blox requested changes

2022-11-14 15:22 UTC, lior-blox commented on README.md
> +[SSV Network ABI](https://bloxapp.github.io/ssv-network/abi/20001/SSVNetwork.json)
add an example and a template

2022-11-15 14:41 UTC, andrew-blox commented on README.md
> +[SSV Network ABI](https://bloxapp.github.io/ssv-network/abi/20001/SSVNetwork.json)
Updated to use a URL template format

2022-11-17 15:58 UTC, merged