Extra names
bloxapp/ssv-network pull request #163
Opened 2023-01-08 10:19 UTC by vadiminc

2023-01-09 12:47 UTC, andrew-blox requested changes

2023-01-09 12:47 UTC, andrew-blox commented on contracts/SSVNetwork.sol
> +            revert NoValidatorOwnershipned();
Think its supposed to be NoValidatorOwnership

2023-01-10 10:52 UTC, andrew-blox approved these changes

2023-01-10 13:47 UTC, mtabasco approved these changes

2023-01-10 14:31 UTC, merged