Change contracts structure
bloxapp/ssv-network pull request #176
Opened 2023-01-27 15:15 UTC by mtabasco

- Create SSVNetworkViews contract
- Create libraries to manage functionalities of Cluster, Operator and Network
- Add deployment test cases
- Update deployment scripts
- Reorganize interfaces

2023-02-02 09:21 UTC, andrew-blox requested changes
I suggest to move the test folder with the .sol files to tests folder for better organization or maybe you cant because hardhat wont find the contracts like this?
Just making sure I see deploy is under test folder which means it will be included in actions

2023-02-02 09:21 UTC, andrew-blox commented on scripts/validate-upgrade-ssv-network-views.ts
> +main()
maybe to change main to something more specific like you did with scripts/upgrade-ssv-network.ts

2023-02-02 09:28 UTC, mtabasco commented
> 
@andrew-blox yes, I tried to move contracts used in tests to the `test` folder but for now hardhat doesn't support many `sources` of contracts. I can leave the folder name `test` or `mock` could be better. Also I will update the names of the contracts used for testing to be more descriptive.

2023-02-08 08:28 UTC, andrew-blox approved these changes

2023-02-08 15:46 UTC, lior-blox approved these changes

2023-02-08 15:47 UTC, merged