2 step transfer ownership - IO1-434
bloxapp/ssv-network pull request #180
Opened 2023-02-01 13:12 UTC by mtabasco

Use OZ's `Ownable2StepUpgradeable` to support 2-step transfer ownership functionality

2023-02-13 13:19 UTC, mtabasco commented on test/dao/operational.ts
> +    it('starting the transfer process does not change owner', async () => {
uppercase and format.
add one test about change onlyOwner variable and try to change with the old owner

2023-02-15 12:42 UTC, andrew-blox requested changes

2023-02-15 12:42 UTC, andrew-blox commented on scripts/upgrade-ssv-network-views.ts
> +  const proxyAddress: any = process.env.SSVNETWORKVIEWS_PROXY_ADDRESS;
Not huge fan of anys, if you must well keep it but lets try to always make a type if needed (no ts-ignore either)

2023-02-15 12:42 UTC, andrew-blox commented on scripts/upgrade-ssv-network.ts
> +  const proxyAddress: any = process.env.SSVNETWORK_PROXY_ADDRESS;
Not huge fan of anys, if you must well keep it but lets try to always make a type if needed (no ts-ignore either)

2023-02-15 12:42 UTC, andrew-blox commented on scripts/validate-upgrade-ssv-network-views.ts
> +  const proxyAddress: any = process.env.SSVNETWORKVIEWS_PROXY_ADDRESS;
Not huge fan of anys, if you must well keep it but lets try to always make a type if needed (no ts-ignore either)

2023-02-15 12:42 UTC, andrew-blox commented on scripts/validate-upgrade-ssv-network.ts
> +  const proxyAddress: any = process.env.SSVNETWORK_PROXY_ADDRESS;
Not huge fan of anys, if you must well keep it but lets try to always make a type if needed (no ts-ignore either)

2023-02-15 12:42 UTC, andrew-blox commented on test/dao/operational.ts
> +let ssvNetworkContract: any;
Not huge fan of anys, if you must well keep it but lets try to always make a type if needed (no ts-ignore either)

2023-02-15 12:42 UTC, andrew-blox commented on README.md
> +Like on the deployment process, you will be guided to the steps for creating or reusing a git tag for the new upgrade.
remove "on"

"Like the deployment process"

2023-02-15 12:42 UTC, andrew-blox commented on README.md
> +Like on the deployment process, you will be guided to the steps for creating or reusing a git tag for the new upgrade.
remove "on"

"Like the deployment process"

2023-02-15 14:46 UTC, lior-blox approved these changes

2023-02-20 13:31 UTC, andrew-blox approved these changes

2023-02-21 11:19 UTC, merged