Git tags - IO1-2235
bloxapp/ssv-network pull request #184
Opened 2023-02-10 12:13 UTC by mtabasco

Add  git tag support.
- On every deployment and upgrade, the the tagging process is presented
- Tag naming follows semantic versioning

TODO: After merging [Versioned contract](https://github.com/bloxapp/ssv-network/pull/179), the tag created will be passed as the version of the contract to the `initialize` function so tags and contract versions are in sync.

2023-02-15 12:29 UTC, mtabasco reviewed
all done

2023-02-15 13:55 UTC, andrew-blox requested changes

2023-02-15 13:55 UTC, andrew-blox commented on scripts/validate-upgrade-ssv-network-views.ts
> +  const proxyAddress: any = process.env.SSVNETWORKVIEWS_PROXY_ADDRESS;
no any :)

2023-02-15 13:55 UTC, andrew-blox commented on scripts/validate-upgrade-ssv-network.ts
> +  const proxyAddress: any = process.env.SSVNETWORK_PROXY_ADDRESS;
again

2023-02-15 13:55 UTC, andrew-blox commented
I have not tested this live yet just reviewed the code.

2023-02-15 14:26 UTC, mtabasco commented on scripts/validate-upgrade-ssv-network.ts
> +  const proxyAddress: any = process.env.SSVNETWORK_PROXY_ADDRESS;
solved in `2-step-transfer` PR, thanks!

2023-02-21 15:29 UTC, lior-blox commented
@mtabasco few things:
1. use the version in the initializer in the contract
2. when selecting an existing/creating tag, git checkout from the tag and deploy that code

2023-02-21 15:29 UTC, lior-blox commented on README.md
> +
.

2023-02-21 15:30 UTC, lior-blox requested changes
.

2023-03-11 00:28 UTC, closed without merging