A validator can voluntarily exit
bloxapp/ssv-network pull request #263
Opened 2023-09-22 00:03 UTC by mtabasco

Allow a validator to start the exit procedure. Reference: [Link](https://github.com/bloxapp/SIPs/blob/main/sips/voluntary_exit.md)

2023-09-22 00:05 UTC, mtabasco commented on contracts/modules/SSVClusters.sol
> -        bytes32 hashedValidator = keccak256(abi.encodePacked(publicKey, msg.sender));
This part was refactored and moved into `ValidatorLib`

2023-09-27 09:31 UTC, andrew-blox commented on contracts/modules/SSVClusters.sol
> +    }
@lior-blox At what point do we minus the validator from the operator list?  If we dont, cant it be a hack that people can fill an operator with 500 validators then exit them and the operator is then trapped?

If its not dkg then how are you going to generate a keystore to perform the exit without a mnemonic?  Also how will it know the validators index (not beacon index but validator index from the mnemonic)

Also what if someone does this contract call to exit then does resharing with new operators with dkg right after this call?

2023-09-27 09:37 UTC, andrew-blox requested changes

2023-09-27 09:37 UTC, andrew-blox commented on test/validators/others.ts
> +    });
Please readjust the title to:
Exiting a validator with incorrect operators (unsorted list) reverts with "IncorrectValidatorState"

2023-09-27 09:37 UTC, andrew-blox commented on test/validators/others.ts
> +    it('Exiting a validator with the wrong operator setup reverts "IncorrectValidatorState"', async () => {
Please readjust the title to:
Exiting a validator with incorrect operators (too many operators) reverts with "IncorrectValidatorState"

2023-09-27 09:37 UTC, andrew-blox commented on test/validators/others.ts
> +    it('Exiting a validator with the wrong operator setup reverts "IncorrectValidatorState"', async () => {
Please add another test where you use operators 1,2,3,5 with title of:
Exiting a validator with incorrect operators (incorrect operator ids with valid amount) reverts with "IncorrectValidatorState"

2023-09-27 11:20 UTC, andrew-blox requested changes

2023-09-27 11:20 UTC, andrew-blox commented on contracts/SSVNetwork.sol
> +    function exitValidator(bytes calldata publicKey, uint64[] calldata operatorIds) external override {
@lior-blox i believe we missing a param here of withdraw address thats wanted.  I dont think its good that we assume owner wants to receive to this address, especially with DKG, i assume with DKG that some validators will be created with some sort of multisig and maybe they dont want to withdraw there.

2023-09-27 11:40 UTC, andrew-blox commented on contracts/SSVNetwork.sol
> +    function exitValidator(bytes calldata publicKey, uint64[] calldata operatorIds) external override {
This is irrelevant as we are not setting the withdraw address anyway.

2023-09-27 12:40 UTC, andrew-blox approved these changes

2023-09-29 09:51 UTC, merged